### ISSUE TITLE
redundant assertion 

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#10]
https://github.com/JackWolf24/ithilfe/blob/5b58b113978753405165dd761bf7ffd0e24d6a3b/tests/it_hilfe4_test.py#L43

du hast davor schon noch aussagekräftiger assertion wie 
   ` assert it_hilfe4.getAvailable([1, 2, 3]) == 1`

dass     `assert type(it_hilfe4.getAvailable([1, 2, 3])) is int` macht weniger sinn.

ähnlich wie 
du weiß es schon ein PKW von audi ist, aber danach bist du immer noch nicht sicher, ob es überhaupt ein Auto ist.

**Comment by BruderJarck** [comment]
Ok ich habe es geändert.
Deine Vergleiche verschönern mir wirklich den tag xD.
