### ISSUE TITLE
import * ist nicht empfohlen 

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#11]
https://github.com/JackWolf24/ithilfe/blob/5b58b113978753405165dd761bf7ffd0e24d6a3b/tests/it_hilfe4_test.py#L2

importier was du brauchst

**Comment by BruderJarck** [comment]
Danke, habs geändert.

aber was ist das problem mit import *?

**Comment by BruderJarck** [comment]
ups

**Comment by shuaimilo** [comment]
> Danke, habs geändert.
> 
> aber was ist das problem mit import *?

import conflict

z.b 
in pytest there is ein function heißt func1
in andere lib z.b cobacore gibt es auch eine function heißt func1

wenn du so importiert

from pytest import *
from cobacore import *

vielleicht möchtest du eigentlich func1 von pytest benutzen, aber hier wird die func1 von cobacore benutzt

from lib import * ist so wie zu sagen, lieg bitte alle bauteile von audi a4 und alle bauteile von bmw 3er in einem Zimmer. Es kann dann sein, du bist selbst verwirrt, welche bauteile du benutzen sollest, wenn manche bauteile ählich sind.

**Comment by BruderJarck** [comment]
ah ok gut danke
