### ISSUE TITLE
consistent return type 

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#12]
https://github.com/JackWolf24/ithilfe/blob/bd0dd4fb6d9c923da2e9403d4330cf6cfd29ca84/it_hilfe/it_hilfe4.py#L65

am best einheitlich type für return value. hier wird manchmal str manchmal list manchmal none sein

**Comment by BruderJarck** [comment]
ok, wiso ist das am besten?, bzw was ist der unterschied?

**Comment by shuaimilo** [comment]
> ok, wiso ist das am besten?, bzw was ist der unterschied?

stell mal vor, du willst eine funktion 'add' benutzen, wird es einfacher für dich dass die funktion nur nummer return anstatt manchmal nummer manchmal string manchmal eine liste, oder? 

anderen beispiel, du gehst zu einer verkäuferin in kaufland um was zu fragen. die verkäuferin antwort machmal auf deutsch, machmal auf english, machmal auf japanisch. Eine logische Konsequenz wäre, nächstes mal fragst du nicht mehr die verkäuferin, sondern andere, die immer auf deutsch antworten, oder?

**Comment by BruderJarck** [comment]
meintest du so wie im letzten commit?

**Comment by shuaimilo** [comment]
> meintest du so wie im letzten commit?

bitte ein bisschen genauer

**Comment by BruderJarck** [comment]
`return [a]`
das?

**Comment by shuaimilo** [comment]
> `return [a]`
> das?

ich meine 

manchmal return `'\033[91m' + "already taken dev name\n" + '\033[0m'`

manchmal return `[newDeviceType, newDeviceName, new.user, new.OS]`

**Comment by BruderJarck** [comment]
`content = [newdevicetype, newdevicename, new.user, new.OS]  # for testing purposes`
`    else:`
`        content = ['\033[91m' + "already taken dev name\n" + '\033[0m']`
`    return content`
    
   besser?

**Comment by BruderJarck** [comment]
already fixed in d2b1a7c139ea30013fc33d167682d91643cc237c
