### ISSUE TITLE
redundant assertion of exception type

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#14]
https://github.com/JackWolf24/ithilfe/blob/d2b1a7c139ea30013fc33d167682d91643cc237c/tests/it_hilfe4_test.py#L50

same assertion is already done with `with raises(IndexError) as Error:`

if you want to asset more you can asset the message

**Comment by BruderJarck** [comment]
ok good to know 
fixed in 5915080f2037555498864719b699f4df7019d03b
