### ISSUE TITLE
careless coding? 

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#15]
https://github.com/JackWolf24/ithilfe/blob/d2b1a7c139ea30013fc33d167682d91643cc237c/tests/it_hilfe4_test.py#L32

the test itself says `test_macbook` but inside the test it still uses `WindowsLapTop`?

**Comment by BruderJarck** [comment]
oh thats terrible 
fixed in 5915080f2037555498864719b699f4df7019d03b
