### ISSUE TITLE
return type

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#17]
https://github.com/JackWolf24/ithilfe/blob/d2b1a7c139ea30013fc33d167682d91643cc237c/it_hilfe/it_hilfe4.py#L87

would it be good to just return the instance itself instead of a string representation?

**Comment by BruderJarck** [comment]
youre right, it acrually made no sens to return the srting rep. 
fixed in 3a3def86aa20610003266d53fe5bd5aad291a052
