### ISSUE TITLE
wrong value can be set to OS

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#18]
https://github.com/JackWolf24/ithilfe/blob/d2b1a7c139ea30013fc33d167682d91643cc237c/it_hilfe/it_hilfe4.py#L82

if you run the code and try to change parameter, you will notice that you can assign any value for OS for your device.
for example you can set a WindowsWorkStatio  macos

**Comment by BruderJarck** [comment]
youre right, I'll fix that.

**Comment by BruderJarck** [comment]
fixed in:
https://github.com/JackWolf24/ithilfe/commit/3a3def86aa20610003266d53fe5bd5aad291a052
