### ISSUE TITLE
bad practice for too tight coupling 

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#19]
https://github.com/JackWolf24/ithilfe/blob/d2b1a7c139ea30013fc33d167682d91643cc237c/it_hilfe/it_hilfe4.py#L105

paramtype = get_available(str(registered_devices.get(name)).split(", ")[1:]) 

this logic depends on heavily of the string representation of class, which is IMHO not necessary and only causes yourself maintenance overhead in the future!

**Comment by BruderJarck** [comment]
I came up with a solution I'm not too sure about if its the propper way to do it. But so far it works just fine. 
In 27dc0b31b33a523c7ef3d2d08edab2e7aef68a0f
