### ISSUE TITLE
Typeerror

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#20]
https://github.com/JackWolf24/ithilfe/blob/b2c801e24b384158371995f45232af5ff98e684c/it_hilfe/it_hilfe4.py#L102

You will get something like `TypeError: can only concatenate str (not "WindowsLapTop") to str`

**Comment by BruderJarck** [comment]
thx, that was kind of embarrassing.
Fixed in 54140ccf0ef015b5c8207bde1137b02d9b5682e5
