### ISSUE TITLE
wrong input check

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#21]
https://github.com/JackWolf24/ithilfe/blob/54140ccf0ef015b5c8207bde1137b02d9b5682e5/it_hilfe/it_hilfe4.py#L84

it seems that I can input negative number without any error
for example 
```
1:WindowsLapTop
2:WindowsWorkStation
3:Macbook
>-2
enter devicename 
already taken: None
```

**Comment by BruderJarck** [comment]
indeed

**Comment by BruderJarck** [comment]
fixed in 
431dd1e92a74e5f464ca12ec6e0cbb50c660f78d

added test in:
2e26bd6623159fbdeb76b6680bc9b8f0065c7079
