### ISSUE TITLE
too wide exception handling

### ISSUE THREAD

**Issue by shuaimilo** [JackWolf24/ithilfe#22]
https://github.com/JackWolf24/ithilfe/blob/54140ccf0ef015b5c8207bde1137b02d9b5682e5/it_hilfe/it_hilfe4.py#L107

exception handling should be kept in a small scope when possible

the current wide exception handling leads to a problem that when user input is wrong, the program doesn't give user a second chance to correct his input 

like 

enter username 
```
>a
1:Win10
2:Win7
>d
index can only be int and must belong to range of available choices

1:search by username
2:register new
3:view all
4:change parameter
5:quit program

```

it would be good that after user typed a wrong index d, the program give user a second chance to again input a number in right range instead of just jumping from the very beginning again.

Just imaging you are writing a text in word. you have input like 1000 words and made one single mistake, and word will tell you that you have made an error and delete all the 1000 words you have already written. not a very good user experience right?

**Comment by BruderJarck** [comment]
that would indeed be annoying

**Comment by BruderJarck** [comment]
fixed in:
431dd1e92a74e5f464ca12ec6e0cbb50c660f78d
I solved it with recursion, but im not sure about the way I implemented the testing.
Please have a look.

**Comment by BruderJarck** [comment]
now I changed to a easy to test while approach for the same problem. 
Now the option functions contain pure logic, exception handling and the handling wrong input re-inputs happens in main function.

**Comment by BruderJarck** [comment]
since my version even got a line less ;D, I'll close this issue
